// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using VlearnBackend2.Contexts;

#nullable disable

namespace VlearnBackend2.Migrations
{
    [DbContext(typeof(PlataformaContext))]
    [Migration("20231110025704_InitialInsert")]
    partial class InitialInsert
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VlearnBackend2.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LoginId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("TelefoneId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoPcd")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasAnnotation("Relational:JsonPropertyName", "tipo_pcd");

                    b.HasKey("Id");

                    b.HasIndex("LoginId");

                    b.HasIndex("TelefoneId");

                    b.ToTable("TABLE_VLEARN_ALUNO");
                });

            modelBuilder.Entity("VlearnBackend2.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Descricao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Duracao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Preco")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("TABLE_VLEARN_CURSO");
                });

            modelBuilder.Entity("VlearnBackend2.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Senha")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TABLE_VLEARN_LOGIN");
                });

            modelBuilder.Entity("VlearnBackend2.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Experiencia")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Formacao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Idiomas")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("LoginId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("TelefoneId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("LoginId");

                    b.HasIndex("TelefoneId");

                    b.ToTable("TABLE_VLEARN_PROFESSOR");
                });

            modelBuilder.Entity("VlearnBackend2.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ddd")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Ddi")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nr_telefone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TABLE_VLEARN_TELEFONE");
                });

            modelBuilder.Entity("VlearnBackend2.Models.Aluno", b =>
                {
                    b.HasOne("VlearnBackend2.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId");

                    b.HasOne("VlearnBackend2.Models.Telefone", "Telefone")
                        .WithMany()
                        .HasForeignKey("TelefoneId");

                    b.Navigation("Login");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("VlearnBackend2.Models.Curso", b =>
                {
                    b.HasOne("VlearnBackend2.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("VlearnBackend2.Models.Professor", b =>
                {
                    b.HasOne("VlearnBackend2.Models.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginId");

                    b.HasOne("VlearnBackend2.Models.Telefone", "Telefone")
                        .WithMany()
                        .HasForeignKey("TelefoneId");

                    b.Navigation("Login");

                    b.Navigation("Telefone");
                });
#pragma warning restore 612, 618
        }
    }
}
